name: Publish Images

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_PASSWORD }}
    - name: Tag and Push
      run: make publish publish-latest
